### PR TITLE
Update to new config format

### PR DESCRIPTION
**Pull request by qm3ster**

### CODE REVIEW

**Comment by jasonkarns** [comment]
needs a rename of `sourceMap` to `sourcemap` as well

**Comment by qm3ster** [comment]
@jasonkarns done

**Comment by yonester** [comment]
*bump* to get this PR reviewed and merged if you have a minute. I think this project is really useful, especially for beginners or as a project starting point. Getting it up-to-date with Rollup is a good idea.

**Comment by qm3ster** [comment]
@eventualbuddha THANK

**Pull request merged**
